#!/usr/bin/env sh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

nvm use --silent

pnpm run docs:sync-version
git add docs/index.html docs/documentation.html

pnpm lint-staged
